version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book_api
    ports:
      - 8000:8080
    restart: on-failure
    depends_on:
      - postgresql
    networks:
      - fullstack

  postgresql:
    image: postgres:latest
    container_name: db_postgresql
    env_file: ./config/db/env
    volumes:
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_postgresql:/var/lib/postgresql/data      
    networks:
      - fullstack

volumes:
  db_postgresql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge